server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: backend

  profiles:
    active: dev

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration:
      access-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES}
      refresh-minutes: ${JWT_REFRESH_EXPIRATION_MINUTES}

  storage:
    total-space: 16106127360